//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 01:55:45 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://simplesolution.dev/EmployeeService/")
package simplesolution.dev;
